runs_dir: output/dl3dv/dynamic_angle/032dee9fb0a8bc1b90871dc5fe950080d0bcd3caf166447f44e60ca50ac04ec7
example_name: statue_in_city

seed: 1
depth_conditioning: True

use_gpt: False
debug: False

# depth model and camera/depth parameters
depth_model: marigold
camera_speed: 0.001
fg_depth_range: 0.015
depth_shift: 0.001
sky_hard_depth: 0.02
init_focal_length: 185

# first run will need sky generation
gen_sky_image: False
gen_sky: False

# enable layer-wise generation
gen_layer: True
# load previously generated gaussians
load_gen: False

