runs_dir: output/dl3dv/indoor/eb4cf52988f805e6fce11d1b239fa9de32eb157364cff06ebac0aa50e0a46567
example_name: elegant_event_space

seed: 1
depth_conditioning: True

use_gpt: False
debug: False

# depth model and camera/depth parameters
depth_model: marigold
camera_speed: 0.001
fg_depth_range: 0.015
depth_shift: 0.001
sky_hard_depth: 0.02
init_focal_length: 960

# first run will need sky generation
gen_sky_image: True
gen_sky: False

# enable layer-wise generation
gen_layer: True
# load previously generated gaussians
load_gen: False

