runs_dir: output/dl3dv/indoor/ec305787b70029b782c71c1bf296c3885c7c22619e5661bd40085533ddfee5e4
example_name: entrance_lobby

seed: 1
depth_conditioning: True

use_gpt: False
debug: False

# depth model and camera/depth parameters
depth_model: marigold
camera_speed: 0.001
fg_depth_range: 0.015
depth_shift: 0.001
sky_hard_depth: 0.02
init_focal_length: 185

# first run will need sky generation
gen_sky_image: True
gen_sky: False

# enable layer-wise generation
gen_layer: True
# load previously generated gaussians
load_gen: False

